version: "3.8"

services:
  front:
    image: messenger-front
    container_name: messenger-front-container
    build:
      context: ./client
    volumes:
      - frontend-build:/build

  back:
    build:
      image: messenger-back
      container_name: messenger-back-container
      context: ./server
    volumes:
      - frontend-build:/build
      - ./server/src/database:/server/src/database
    ports:
      - "7005:7005"
    depends_on:
      - msg-front
    deploy:
      resources:
        limits:
          memory: 120M
    restart: on-failure

volumes:
  frontend-build:
