version: "3.8"

services:
  front:
    image: messenger-front
    container_name: messenger-front-container
    build:
      context: ./client
    volumes:
      - frontend-build:/build

  back:
    image: messenger-back
    container_name: messenger-back-container
    build:
      context: ./server
    volumes:
      - frontend-build:/build
      - ./server/src/database:/server/src/database
    ports:
      - "7004:7004"
    depends_on:
      - front
    deploy:
      resources:
        limits:
          memory: 250M
    restart: always
    networks:
      - shared-pet

volumes:
  frontend-build:

networks:
  shared-pet:
    external: true
